name: Merge AdGuard Rules

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  merge_rules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          pip install requests

      - name: Download Official Rules
        run: |
          python .github/scripts/download_rules.py --type official

      - name: Download Third-Party Rules
        run: |
          python .github/scripts/download_rules.py --type third_party

      - name: Merge And Deduplicate
        run: |
          # 合并自定义第三方规则
          cat ziyongdnsZ > ziyongdnsZ_temp
          cat ziyongrulerZ > ziyongrulerZ_temp
          #AdguardDNS_temp
          cat AdguardDNS_temp >> ziyongdnsZ_temp
          cat AdguardRuler_temp >> ziyongrulerZ_temp

          # 清理重复并保存
          sort -u ziyongdnsZ_temp > ziyongdnsZ1
          sort -u ziyongrulerZ_temp > ziyongrulerZ1
          rm ziyongdnsZ_temp ziyongrulerZ_temp

      - name: Optimize Rules
        run: |
          python .github/scripts/optimize_rules.py

      - name: Commit and Push Changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add ziyongdns ziyongruler
          git commit -m "Updated AdGuard rules" || echo "No changes to commit"
          git push origin HEAD:main